### ISSUE TITLE
Incompatible with symfony 2.1.9-dev

### ISSUE THREAD

**Issue by pghoratiu** [vbardales/MultipleAppKernelBundle#5]
Found an incompatibility with this bundle and Symfony 2.1.9-dev installed via composer.

The cache path for the routing file was changed, from 

   appprodUrlGenerator.php -> appProdUrlGenerator.php

I had to change the following in Routing/Generator.php
 ```
--- a/Routing/Generator.php
+++ b/Routing/Generator.php
@@ -56,7 +56,8 @@ class Generator
     {
         // Load the route generator for app
         $cache_dir = str_replace($this->container->getParameter('kernel.name'), $appName, $this->container->getParameter('kernel.cache_dir'));
-        $generatorClassName = $appName.$this->container->getParameter('kernel.environment').'UrlGenerator';
+        $generatorClassName = $appName.ucfirst($this->container->getParameter('kernel.environment')).'UrlGenerator';
```

This is the comit that I think brakes it:
https://github.com/symfony/FrameworkBundle/commit/38602e18e219631e556fe1c700dca022a3f2cbd2

**Comment by quentinsikana** [comment]
Could you merge bc2c96f3b15fed3cf9afc96947f2f4a7f0e348aa to correct this please ?

**Comment by quentinsikana** [comment]
Pull request #6 resolves this.
@vbardales

**Comment by vbardales** [comment]
Done!
