### ISSUE TITLE
AppUrlGenerator: appName gets replaced in the path

### ISSUE THREAD

**Issue by quentinsikana** [vbardales/MultipleAppKernelBundle#7]
Hi @vbardales !
First of all, thank you for your bundle it works great!

I noticed a case which can be problematic in `KernelBundle/Routing/Generator.php`

To generate the var `$cache_dir` the following code is used :
```
// Load the route generator for app 
$cache_dir = str_replace($this->container->getParameter('kernel.name'), $appName, $this->container->getParameter('kernel.cache_dir'));
```

We encountered a problem in production since we have one of our app which is called `tv` and in our path we have `/vhosts/mysite.tv/www/...` so the `.tv`got replaced by this line !

We figured out a quick fix, here it is :
```
// Load the route generator for app
$kernelName = '/'.$this->container->getParameter('kernel.name').'/';
$appName = '/'.$appName.'/';
$cache_dir = str_replace($kernelName, $appName, $this->container->getParameter('kernel.cache_dir'));
```

We just added slashes before and after appName to avoid replacing it by mistake in the full path.

This is not the most elegant solution but if fixes the problem for now and prevents our visitors to get an error 500.

I am opening a pull request with my fix but if you have another idea to fix this, suggestions are welcomed !

**Comment by quentinsikana** [comment]
PR #8 is opened !

**Comment by vbardales** [comment]
Seems a good option, another symbol than slash (like pipe) would probably have been perhaps more generic, but whatever symbol it is, that's ok, I guess. Merged :)

**Comment by quentinsikana** [comment]
Wow that was fast, thank you! 👍

**Comment by quentinsikana** [comment]
Detected a little bug in my modifications : 

The `$generatorClassName` was wrong since `$appName` var was replaced with the slashes.

I added a temporary var to correct this in PR #9.

Sorry for bothering with several pull requests. :(
